modified workflow for exceed storage

diff --git a/.github/workflows/abhi-frontend-deploy.yml b/.github/workflows/abhi-frontend-deploy.yml
--- a/.github/workflows/abhi-frontend-deploy.yml
+++ b/.github/workflows/abhi-frontend-deploy.yml
@@ -55,10 +55,10 @@ jobs:
         cd MozartUI-Dev
         npm install --legacy-peer-deps
       
-    - name: Build the project
-      run: |
-        cd MozartUI-Dev
-        npm run build --prod
+    # - name: Build the project
+    #   run: |
+    #     cd MozartUI-Dev
+    #     npm run build --prod
 
     # - name: List Build Artifacts
     #   run: ls -la dist/frontend
@@ -69,71 +69,85 @@ jobs:
         ls -la 
         ls -la MozartUI-Dev
         ls -la MozartUI-Dev/dist
+
+    - name: Remove artifacts
+        # You may pin to the exact commit or the version.
+        # uses: c-hive/gha-remove-artifacts@24dc23384a1fa6a058b79c73727ae0cb2200ca4c
+      uses: c-hive/gha-remove-artifacts@v1.2.0
+      with:
+        # Artifacts older than this will be deleted (e.g. "2 months", "1 day"). Parsed by moment.
+        age: "1 day"
+        # Access token for the repository, available under the same name in secrets.
+        GITHUB_TOKEN: ${{ github.token }}
+        # true/false. If enabled, tag build artifacts (e.g. release artifacts) will be kept.
+        skip-tags: false
+        # Keep the specified number of artifacts even if they are older than the age.
+        skip-recent: 1
       
-    - name: Upload build artifacts
-      uses: actions/upload-artifact@v3
-      with:
-        name: angular-artifacts
-        path: ./MozartUI-Dev/dist/
+#     - name: Upload build artifacts
+#       uses: actions/upload-artifact@v3
+#       with:
+#         name: angular-artifacts
+#         path: ./MozartUI-Dev/dist/
 
-    - name: SonarQube Scan
-      uses: sonarsource/sonarqube-scan-action@v3.0.0
-      with:
-        projectBaseDir: .
-        args: |
-          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
-          -Dsonar.sources=./MozartUI-Dev/src
-      env:
-        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+#     - name: SonarQube Scan
+#       uses: sonarsource/sonarqube-scan-action@v3.0.0
+#       with:
+#         projectBaseDir: .
+#         args: |
+#           -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
+#           -Dsonar.sources=./MozartUI-Dev/src
+#       env:
+#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
-    - name: Check SonarQube Quality Gate
-      run: |
-        status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
-          "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ env.SONAR_PROJECT_KEY }}" \
-          | jq -r .projectStatus.status)
-        echo "Quality Gate status: $status"
-        if [ "$status" != "OK" ]; then
-          echo "Quality Gate failed: $status"
-          exit 1
-        fi
+#     - name: Check SonarQube Quality Gate
+#       run: |
+#         status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
+#           "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ env.SONAR_PROJECT_KEY }}" \
+#           | jq -r .projectStatus.status)
+#         echo "Quality Gate status: $status"
+#         if [ "$status" != "OK" ]; then
+#           echo "Quality Gate failed: $status"
+#           exit 1
+#         fi
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs: build
+#   deploy:
+#     runs-on: ubuntu-latest
+#     needs: build
 
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 10
+#     steps:
+#     - name: Checkout code
+#       uses: actions/checkout@v3
+#       with:
+#         fetch-depth: 10
 
-    - name: Set up SSH
-      run: |
-        mkdir -p ~/.ssh
-        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
-        chmod 600 ~/.ssh/id_rsa
+#     - name: Set up SSH
+#       run: |
+#         mkdir -p ~/.ssh
+#         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+#         chmod 600 ~/.ssh/id_rsa
 
-    - name: Add VM to known hosts
-      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
+#     - name: Add VM to known hosts
+#       run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
 
-    - name: Create deployment directory on VM
-      run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"if (-Not (Test-Path -Path '$DEPLOY_BASE_DIR/$GITHUB_SHA')) { New-Item -Path '$DEPLOY_BASE_DIR/$GITHUB_SHA' -ItemType Directory }\""
+#     - name: Create deployment directory on VM
+#       run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"if (-Not (Test-Path -Path '$DEPLOY_BASE_DIR/$GITHUB_SHA')) { New-Item -Path '$DEPLOY_BASE_DIR/$GITHUB_SHA' -ItemType Directory }\""
 
-    - name: Manage Previous Deployments (Keep Last 3)
-      run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"\$deploymentDir = '$DEPLOY_BASE_DIR'; \$deployments = Get-ChildItem -Path \$deploymentDir | Sort-Object LastWriteTime -Descending; if (\$deployments.Count -gt 3) { \$deployments | Select-Object -Skip 3 | Remove-Item -Recurse -Force }\""
+#     - name: Manage Previous Deployments (Keep Last 3)
+#       run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"\$deploymentDir = '$DEPLOY_BASE_DIR'; \$deployments = Get-ChildItem -Path \$deploymentDir | Sort-Object LastWriteTime -Descending; if (\$deployments.Count -gt 3) { \$deployments | Select-Object -Skip 3 | Remove-Item -Recurse -Force }\""
 
-    - name: Download build artifacts
-      uses: actions/download-artifact@v3
-      with:
-        name: angular-artifacts
-        path: ./MozartUI-Dev/dist/
+#     - name: Download build artifacts
+#       uses: actions/download-artifact@v3
+#       with:
+#         name: angular-artifacts
+#         path: ./MozartUI-Dev/dist/
 
-    - name: Upload artifact to VM
-      run: scp -i ~/.ssh/id_rsa -P 22 -r ./dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$DEPLOY_BASE_DIR/$GITHUB_SHA/
+#     - name: Upload artifact to VM
+#       run: scp -i ~/.ssh/id_rsa -P 22 -r ./dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$DEPLOY_BASE_DIR/$GITHUB_SHA/
 
-    - name: Deploy application on IIS
-      run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"if (-Not (Get-WebSite -Name 'AngularApp')) { New-WebSite -Name 'AngularApp' -Port $PORT -PhysicalPath '$WEB_ROOT' -ApplicationPool 'DefaultAppPool' }\""
+#     - name: Deploy application on IIS
+#       run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"if (-Not (Get-WebSite -Name 'AngularApp')) { New-WebSite -Name 'AngularApp' -Port $PORT -PhysicalPath '$WEB_ROOT' -ApplicationPool 'DefaultAppPool' }\""
 
-    - name: Update IIS Site for the Latest Deployment
-      run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"Stop-WebSite -Name 'AngularApp'; Copy-Item -Path '$DEPLOY_BASE_DIR/$GITHUB_SHA/*' -Destination '$WEB_ROOT' -Recurse; Start-WebSite -Name 'AngularApp'\""
+#     - name: Update IIS Site for the Latest Deployment
+#       run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"Stop-WebSite -Name 'AngularApp'; Copy-Item -Path '$DEPLOY_BASE_DIR/$GITHUB_SHA/*' -Destination '$WEB_ROOT' -Recurse; Start-WebSite -Name 'AngularApp'\""
