modified workflow for aplication pool step issue

diff --git a/.github/workflows/abhi-frontend-deploy.yml b/.github/workflows/abhi-frontend-deploy.yml
--- a/.github/workflows/abhi-frontend-deploy.yml
+++ b/.github/workflows/abhi-frontend-deploy.yml
@@ -202,23 +202,23 @@ jobs:
     
     - name: Create or Update Application Pool
       run: |
-        ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "& {
-          \$AppPoolName = 'FrontendAppPool';
-          try {
-            if (Test-Path 'IIS:\\AppPools\\\$AppPoolName') {
-              Write-Output 'Application Pool ''\$AppPoolName'' already exists. Skipping creation.';
-            } else {
-              Write-Output 'Creating Application Pool: \$AppPoolName';
-              New-WebAppPool -Name \$AppPoolName;
-              Set-ItemProperty IIS:\\AppPools\\\$AppPoolName -Name managedRuntimeVersion -Value 'v4.0';
-              Set-ItemProperty IIS:\\AppPools\\\$AppPoolName -Name processModel.identityType -Value ApplicationPoolIdentity;
-            }
-          } catch {
-            Write-Output 'Error while creating Application Pool: \$AppPoolName';
-            Write-Output \$_.Exception.Message;
-            exit 1;
-          }
-        }"
+       ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command '{
+         $AppPoolName = "FrontendAppPool";
+         try {
+           if (Test-Path "IIS:\\AppPools\\$AppPoolName") {
+             Write-Output "Application Pool `"$AppPoolName`" already exists. Skipping creation.";
+           } else {
+             Write-Output "Creating Application Pool: `"$AppPoolName`"";
+             New-WebAppPool -Name $AppPoolName;
+             Set-ItemProperty IIS:\\AppPools\\$AppPoolName -Name managedRuntimeVersion -Value "v4.0";
+             Set-ItemProperty IIS:\\AppPools\\$AppPoolName -Name processModel.identityType -Value ApplicationPoolIdentity;
+           }
+         } catch {
+           Write-Error "Error while creating Application Pool: `"$AppPoolName`"";
+           Write-Error $_.Exception.Message;
+           exit 1;
+         }
+       }'
 
     - name: Stop IIS Website if Exists
       run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"if (Get-WebSite -Name 'AngularApp' -ErrorAction SilentlyContinue) { Stop-WebSite -Name 'AngularApp' } else { Write-Output 'Website not found' }\""
