modified worflow commented out sonar quality check and trigger on worflow dispatch

diff --git a/.github/workflows/abhi-frontend-deploy.yml b/.github/workflows/abhi-frontend-deploy.yml
--- a/.github/workflows/abhi-frontend-deploy.yml
+++ b/.github/workflows/abhi-frontend-deploy.yml
@@ -1,22 +1,22 @@
 name: Build and Deploy Angular App to Azure VM
 
 on:
-   push:
-     branches:
-       - RV_abhi_frontend_deploy
+  #  push:
+  #    branches:
+  #      - RV_abhi_frontend_deploy
   #     - Dev
   #     - release
-  # workflow_dispatch:
-  #   inputs:
-  #     environment:
-  #       description: 'Deployment environment'
-  #       required: true
-  #       default: 'abhi_dev'
-  #       type: choice
-  #       options:
-  #         - abhi_dev
-  #         - abhi_uat
-  #         - abhi_prod
+  workflow_dispatch:
+    inputs:
+      environment:
+        description: 'Deployment environment'
+        required: true
+        default: 'abhi_dev'
+        type: choice
+        options:
+          - abhi_dev
+          - abhi_uat
+          - abhi_prod
 
 env:
   SONAR_PROJECT_KEY: "frontend-sonar-project"
@@ -104,16 +104,16 @@ jobs:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
-    - name: Check SonarQube Quality Gate
-      run: |
-        status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
-          "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ env.SONAR_PROJECT_KEY }}" \
-          | jq -r .projectStatus.status)
-        echo "Quality Gate status: $status"
-        if [ "$status" != "OK" ]; then
-          echo "Quality Gate failed: $status"
-          exit 1
-        fi
+    # - name: Check SonarQube Quality Gate
+    #   run: |
+    #     status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
+    #       "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ env.SONAR_PROJECT_KEY }}" \
+    #       | jq -r .projectStatus.status)
+    #     echo "Quality Gate status: $status"
+    #     if [ "$status" != "OK" ]; then
+    #       echo "Quality Gate failed: $status"
+    #       exit 1
+    #     fi
 
   deploy:
     runs-on: ubuntu-latest
