checking workflow working

diff --git a/.github/workflows/abhi-frontend-deploy.yml b/.github/workflows/abhi-frontend-deploy.yml
--- a/.github/workflows/abhi-frontend-deploy.yml
+++ b/.github/workflows/abhi-frontend-deploy.yml
@@ -38,21 +38,21 @@ jobs:
       with:
         fetch-depth: 10
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: '18.20.3'
+    # - name: Set up Node.js
+    #   uses: actions/setup-node@v3
+    #   with:
+    #     node-version: '18.20.3'
 
     
-    - name: Cache Node modules
-      uses: actions/cache@v3
-      with:
-        path: |
-          ~/.npm
-          ~/.cache
-        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-        restore-keys: |
-          ${{ runner.os }}-node-
+    # - name: Cache Node modules
+    #   uses: actions/cache@v3
+    #   with:
+    #     path: |
+    #       ~/.npm
+    #       ~/.cache
+    #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+    #     restore-keys: |
+    #       ${{ runner.os }}-node-
 
     # - name: Print working directory and list its contents
     #   run: |
@@ -71,20 +71,20 @@ jobs:
     #     cd MozartUI-Dev
     #     npm install --legacy-peer-deps
 
-    - name: Install dependencies
-      run: |
-        npm install --legacy-peer-deps
+    # - name: Install dependencies
+    #   run: |
+    #     npm install --legacy-peer-deps
 
-    - name: Clean previous build artifacts
-      run: |
-        rm -rf ./dist/*
+    # - name: Clean previous build artifacts
+    #   run: |
+    #     rm -rf ./dist/*
       
-    - name: Build the project
-      run: |
-        npm run build --prod
+    # - name: Build the project
+    #   run: |
+    #     npm run build --prod
 
-    - name: List Build Artifacts
-      run: ls -la ./dist/
+    # - name: List Build Artifacts
+    #   run: ls -la ./dist/
 
     # - name: List contents in the current directory
     #   run: |
@@ -92,25 +92,25 @@ jobs:
     #     ls -la 
     #     ls -la MozartUI-Dev
       
-    - name: Upload build artifacts
-      uses: actions/upload-artifact@v3
-      with:
-        name: angular-artifacts
-        path: ./dist/*
+    # - name: Upload build artifacts
+    #   uses: actions/upload-artifact@v3
+    #   with:
+    #     name: angular-artifacts
+    #     path: ./dist/*
 
-    - name: Debug:List files after downloading artifacts
-      run: ls -l ./dist/
+    # - name: Debug:List files after downloading artifacts
+    #   run: ls -l ./dist/
 
-    - name: SonarQube Scan
-      uses: sonarsource/sonarqube-scan-action@v3.0.0
-      with:
-        projectBaseDir: .
-        args: |
-          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
-          -Dsonar.sources=./src
-      env:
-        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+    # - name: SonarQube Scan
+    #   uses: sonarsource/sonarqube-scan-action@v3.0.0
+    #   with:
+    #     projectBaseDir: .
+    #     args: |
+    #       -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
+    #       -Dsonar.sources=./src
+    #   env:
+    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+    #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
     # - name: Check SonarQube Quality Gate
     #   run: |
@@ -163,56 +163,72 @@ jobs:
       run: |
         echo "Generated version: $TAGGED_VERSION"
   
-    
-    # - name: Create deployment directory on VM
-    #   run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"if (-Not (Test-Path -Path '$DEPLOY_BASE_DIR/$GITHUB_SHA')) { New-Item -Path '$DEPLOY_BASE_DIR/$GITHUB_SHA' -ItemType Directory }\""
+    # - name: Create deployment directory on VM with version
+    #   run: |
+    #     ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "\$DeployDir = '${{ env.DEPLOY_BASE_DIR }}\\$TAGGED_VERSION'; try { if (-Not (Test-Path -Path \$DeployDir)) { Write-Output \"Creating deployment directory: \$DeployDir\"; New-Item -Path \$DeployDir -ItemType Directory; } else { Write-Output \"Deployment directory already exists: \$DeployDir\"; } } catch { Write-Output \"Error while creating deployment directory: \$DeployDir\"; Write-Output \$_.Exception.Message; exit 1; }"
 
-    - name: Create deployment directory on VM with version
-      run: |
-        ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "\$DeployDir = '${{ env.DEPLOY_BASE_DIR }}\\$TAGGED_VERSION'; try { if (-Not (Test-Path -Path \$DeployDir)) { Write-Output \"Creating deployment directory: \$DeployDir\"; New-Item -Path \$DeployDir -ItemType Directory; } else { Write-Output \"Deployment directory already exists: \$DeployDir\"; } } catch { Write-Output \"Error while creating deployment directory: \$DeployDir\"; Write-Output \$_.Exception.Message; exit 1; }"
-
-    - name: Manage Previous Deployments (Keep Last 3)
-      run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"\$deploymentDir = '${{ env.DEPLOY_BASE_DIR }}'; \$deployments = Get-ChildItem -Path \$deploymentDir | Sort-Object LastWriteTime -Descending; if (\$deployments.Count -gt 3) { \$deployments | Select-Object -Skip 3 | Remove-Item -Recurse -Force }\""
+    # - name: Manage Previous Deployments (Keep Last 3)
+    #   run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"\$deploymentDir = '${{ env.DEPLOY_BASE_DIR }}'; \$deployments = Get-ChildItem -Path \$deploymentDir | Sort-Object LastWriteTime -Descending; if (\$deployments.Count -gt 3) { \$deployments | Select-Object -Skip 3 | Remove-Item -Recurse -Force }\""
     
-    - name: Create directory for artifacts
-      run: mkdir -p ./my-artifacts
+    # - name: Create directory for artifacts
+    #   run: mkdir -p ./my-artifacts
       
-    - name: Download build artifacts
-      uses: actions/download-artifact@v3
-      with:
-        name: angular-artifacts
-        path: ./my-artifacts
+    # - name: Download build artifacts
+    #   uses: actions/download-artifact@v3
+    #   with:
+    #     name: angular-artifacts
+    #     path: ./my-artifacts
     
-    - name: Debug:List files after downloading artifacts
-      run: ls -l ./my-artifacts
+    # - name: Debug:List files after downloading artifacts
+    #   run: ls -l ./my-artifacts
 
-    - name: Upload artifact to VM with versioning
-      run: scp -i ~/.ssh/id_rsa -P 22 -r ./my-artifacts/angular-dev/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$DEPLOY_BASE_DIR/$TAGGED_VERSION/
-
+    # - name: Upload artifact to VM with versioning
+    #   run: scp -i ~/.ssh/id_rsa -P 22 -r ./my-artifacts/angular-dev/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$DEPLOY_BASE_DIR/$TAGGED_VERSION/
+#######################
+    # - name: Create or Update Application Pool
+    #   run: |
+    #     ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "$AppPoolName='${{ env.APP_POOL_NAME }}';try {if (Test-Path 'IIS:\\AppPools\\$AppPoolName') {Write-Output \"Application Pool '$AppPoolName' already exists. Skipping creation.\";} else {Write-Output \"Creating Application Pool: $AppPoolName\";New-WebAppPool -Name $AppPoolName;Set-ItemProperty IIS:\\AppPools\\$AppPoolName -Name managedRuntimeVersion -Value 'v4.0';Set-ItemProperty IIS:\\AppPools\\$AppPoolName -Name processModel.identityType -Value ApplicationPoolIdentity;}} catch {Write-Output \"Error while creating Application Pool: $AppPoolName\";Write-Output $_.Exception.Message;exit 1;}"
+########################    
     - name: Create or Update Application Pool
       run: |
-        ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "$AppPoolName='${{ env.APP_POOL_NAME }}';try {if (Test-Path 'IIS:\\AppPools\\$AppPoolName') {Write-Output \"Application Pool '$AppPoolName' already exists. Skipping creation.\";} else {Write-Output \"Creating Application Pool: $AppPoolName\";New-WebAppPool -Name $AppPoolName;Set-ItemProperty IIS:\\AppPools\\$AppPoolName -Name managedRuntimeVersion -Value 'v4.0';Set-ItemProperty IIS:\\AppPools\\$AppPoolName -Name processModel.identityType -Value ApplicationPoolIdentity;}} catch {Write-Output \"Error while creating Application Pool: $AppPoolName\";Write-Output $_.Exception.Message;exit 1;}"
-    
-    - name: Stop and Remove IIS Website if Exists
-      run: |
-        ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "if (Get-WebSite -Name '${{ env.SITE_NAME }}' -ErrorAction SilentlyContinue) {Write-Output 'Stopping and Removing Website: ${{ env.SITE_NAME }}';Stop-WebSite -Name '${{ env.SITE_NAME }}';Remove-WebSite -Name '${{ env.SITE_NAME }}';} else {Write-Output 'Website not found, skipping stop and remove.';}"
-    
-    - name: Ensure Frontend Directory Exists (Web Root)
-      run: |
-        ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "if (-Not (Test-Path -Path '${{ env.WEB_ROOT }}')) {Write-Output 'Creating frontend directory: ${{ env.WEB_ROOT }}';New-Item -Path '${{ env.WEB_ROOT }}' -ItemType Directory;} else {Write-Output 'Directory already exists: ${{ env.WEB_ROOT }}';}"
-    
-    - name: Clean up the Frontend Directory
-      run: |
-        ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "Write-Output 'Cleaning up frontend directory: ${{ env.WEB_ROOT }}';try {$lockedFiles=Get-Process | Where-Object {($_.Modules | Where-Object { $_.FileName -like '${{ env.WEB_ROOT }}\\*'})};if ($lockedFiles) {Write-Output 'Files are currently locked, cleanup skipped.';exit 1;} else {Remove-Item -Path '${{ env.WEB_ROOT }}\\*' -Recurse -Force;}} catch {Write-Output 'Error during cleanup:';Write-Output $_.Exception.Message;exit 1;}"
-    
-    - name: Copy Latest Build to IIS Web Root Directory
-      run: |
-        ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "Write-Output 'Copying latest build to web root directory';if (-Not (Test-Path -Path '${{ env.WEB_ROOT }}')) {Write-Output 'Error: Destination directory does not exist: ${{ env.WEB_ROOT }}';exit 1;}Copy-Item -Path '${{ env.DEPLOY_BASE_DIR }}\\${{ env.TAGGED_VERSION }}\\*' -Destination '${{ env.WEB_ROOT }}' -Recurse -Force;"
-    
-    - name: Deploy New IIS Site
-      run: |
-        ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "Write-Output 'Creating new IIS website';if (-Not (Test-Path -Path '${{ env.DEPLOY_BASE_DIR }}\\${{ env.TAGGED_VERSION }}')) {Write-Output 'Error: Deployment directory does not exist: ${{ env.DEPLOY_BASE_DIR }}\\${{ env.TAGGED_VERSION }}';exit 1;}New-WebSite -Name '${{ env.SITE_NAME }}' -PhysicalPath '${{ env.DEPLOY_BASE_DIR }}\\${{ env.TAGGED_VERSION }}' -ApplicationPool '${{ env.APP_POOL_NAME }}' -Port ${{ env.PORT }} -HostHeader '${{ env.BINDING_HOST }}';"
+        ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command '
+          $AppPoolName="${{ env.APP_POOL_NAME }}";
+          try {
+            if (Test-Path "IIS:\\AppPools\\$AppPoolName") {
+              Write-Output "Application Pool ''$AppPoolName'' already exists. Skipping creation.";
+            } else {
+              Write-Output "Creating Application Pool: $AppPoolName";
+              New-WebAppPool -Name $AppPoolName;
+              Set-ItemProperty IIS:\\AppPools\\$AppPoolName -Name managedRuntimeVersion -Value "v4.0";
+              Set-ItemProperty IIS:\\AppPools\\$AppPoolName -Name processModel.identityType -Value ApplicationPoolIdentity;
+            }
+          } catch {
+            Write-Output "Error while creating Application Pool: $AppPoolName";
+            Write-Output $_.Exception.Message;
+            exit 1;
+          }
+        '
 
+    # - name: Stop and Remove IIS Website if Exists
+    #   run: |
+    #     ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "if (Get-WebSite -Name '${{ env.SITE_NAME }}' -ErrorAction SilentlyContinue) {Write-Output 'Stopping and Removing Website: ${{ env.SITE_NAME }}';Stop-WebSite -Name '${{ env.SITE_NAME }}';Remove-WebSite -Name '${{ env.SITE_NAME }}';} else {Write-Output 'Website not found, skipping stop and remove.';}"
+    
+    # - name: Ensure Frontend Directory Exists (Web Root)
+    #   run: |
+    #     ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "if (-Not (Test-Path -Path '${{ env.WEB_ROOT }}')) {Write-Output 'Creating frontend directory: ${{ env.WEB_ROOT }}';New-Item -Path '${{ env.WEB_ROOT }}' -ItemType Directory;} else {Write-Output 'Directory already exists: ${{ env.WEB_ROOT }}';}"
+    
+    # - name: Clean up the Frontend Directory
+    #   run: |
+    #     ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "Write-Output 'Cleaning up frontend directory: ${{ env.WEB_ROOT }}';try {$lockedFiles=Get-Process | Where-Object {($_.Modules | Where-Object { $_.FileName -like '${{ env.WEB_ROOT }}\\*'})};if ($lockedFiles) {Write-Output 'Files are currently locked, cleanup skipped.';exit 1;} else {Remove-Item -Path '${{ env.WEB_ROOT }}\\*' -Recurse -Force;}} catch {Write-Output 'Error during cleanup:';Write-Output $_.Exception.Message;exit 1;}"
+    
+    # - name: Copy Latest Build to IIS Web Root Directory
+    #   run: |
+    #     ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "Write-Output 'Copying latest build to web root directory';if (-Not (Test-Path -Path '${{ env.WEB_ROOT }}')) {Write-Output 'Error: Destination directory does not exist: ${{ env.WEB_ROOT }}';exit 1;}Copy-Item -Path '${{ env.DEPLOY_BASE_DIR }}\\${{ env.TAGGED_VERSION }}\\*' -Destination '${{ env.WEB_ROOT }}' -Recurse -Force;"
+    
+    # - name: Deploy New IIS Site
+    #   run: |
+    #     ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "Write-Output 'Creating new IIS website';if (-Not (Test-Path -Path '${{ env.DEPLOY_BASE_DIR }}\\${{ env.TAGGED_VERSION }}')) {Write-Output 'Error: Deployment directory does not exist: ${{ env.DEPLOY_BASE_DIR }}\\${{ env.TAGGED_VERSION }}';exit 1;}New-WebSite -Name '${{ env.SITE_NAME }}' -PhysicalPath '${{ env.DEPLOY_BASE_DIR }}\\${{ env.TAGGED_VERSION }}' -ApplicationPool '${{ env.APP_POOL_NAME }}' -Port ${{ env.PORT }} -HostHeader '${{ env.BINDING_HOST }}';"
+#######################################################################################
     # - name: Create or Update Application Pool
     #   run: |
     #     ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "\$AppPoolName = '${{ env.APP_POOL_NAME }}'; try { if (Test-Path 'IIS:\\AppPools\\\$AppPoolName') { Write-Output \"Application Pool '\$AppPoolName' already exists. Skipping creation.\"; } else { Write-Output \"Creating Application Pool: \$AppPoolName\"; New-WebAppPool -Name \$AppPoolName; Set-ItemProperty IIS:\\AppPools\\\$AppPoolName -Name managedRuntimeVersion -Value 'v4.0'; Set-ItemProperty IIS:\\AppPools\\\$AppPoolName -Name processModel.identityType -Value ApplicationPoolIdentity; } } catch { Write-Output \"Error while creating Application Pool: \$AppPoolName\"; Write-Output \$_.Exception.Message; exit 1; }"
@@ -283,31 +299,31 @@ jobs:
     #       Write-Output 'SSL Binding Complete!';
     #       Get-WebBinding -Name \$SiteName | Where-Object { \$_.protocol -eq 'https' }
     #     "
-
-    - name: Start IIS Site
-      run: |
-        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "Start-WebSite -Name '${{ env.SITE_NAME }}'"
-
+################
+    # - name: Start IIS Site
+ ###   #   run: |
+    #     ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} powershell -Command "Start-WebSite -Name '${{ env.SITE_NAME }}'"
+#####################
     # - name: Copy Latest Build to IIS web root directory
     #   run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"Copy-Item -Path '$DEPLOY_BASE_DIR/$TAGGED_VERSION/*' -Destination '$WEB_ROOT' -Recurse -Force\""
     
     # - name: Deploy application on IIS
     #   run: ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "powershell -Command \"New-WebSite -Name 'AngularApp' -Port $PORT -PhysicalPath ('${{ env.WEB_ROOT }}' -replace '/', '\\') -ApplicationPool 'ABHIUP'\""
 
-    - name: Set environment variable based on branch
-      run: |
-        branch_name="${GITHUB_REF#refs/heads/}" # Strip out 'refs/heads/' from branch name
-        environment=${branch_name}
-        if [ "$environment" == "main" ]; then
-          environment="prod"
-        fi
-        echo "ENVIRONMENT=$environment" >> $GITHUB_ENV
+    # - name: Set environment variable based on branch
+    #   run: |
+    #     branch_name="${GITHUB_REF#refs/heads/}" # Strip out 'refs/heads/' from branch name
+    #     environment=${branch_name}
+    #     if [ "$environment" == "main" ]; then
+    #       environment="prod"
+    #     fi
+    #     echo "ENVIRONMENT=$environment" >> $GITHUB_ENV
 
-    - name: Tag the commit
-      if: ${{ success() }}  # Only tag if the workflow is successful
-      run: |
-        TAG="$ENVIRONMENT-$TAGGED_VERSION"
-        echo "Tag: $TAG"  # Debugging the tag value
-        git tag $TAG
-        git push origin $TAG
+    # - name: Tag the commit
+    #   if: ${{ success() }}  # Only tag if the workflow is successful
+    #   run: |
+    #     TAG="$ENVIRONMENT-$TAGGED_VERSION"
+    #     echo "Tag: $TAG"  # Debugging the tag value
+    #     git tag $TAG
+    #     git push origin $TAG
     
